const MIN_TASKS = 3
const MIN_TIME_BETWEEN_ORGANIZATIONS = 1 * 60 * 1000 // 1 minute
const MAX_ORGANIZATIONS_PER_DAY = 10
const MIN_TIME_SINCE_LAST_TASK_ORGANIZATION = 15 * 60 * 1000 // 15 minutes

export { MAX_ORGANIZATIONS_PER_DAY, MIN_TASKS, MIN_TIME_BETWEEN_ORGANIZATIONS, MIN_TIME_SINCE_LAST_TASK_ORGANIZATION }
