const titles = [
  'Parabéns!',
  'Uau!',
  'Magnífico!',
  'Fantástico!',
  'Esplêndido!',
  'Supimpa!',
  'Bom demais!',
  'Merece um troféu!',
]

const quotes = [
  'Adivinha quem é o mestre das tarefas? Sim, você mesmo! Continue brilhando!',
  'Concluindo tarefas como um ninja! Próximo desafio: conquistar o mundo!',
  'Você é uma máquina de produtividade! Dê uma pausa para recarregar seu modo incrível.',
  'Com tanta eficiência, você está prestes a receber um diploma em conclusão de tarefas!',
  'Você é uma estrela cadente da produtividade. Brilhe ainda mais na próxima tarefa!',
  'Parabéns! Seu superpoder de conclusão de tarefas está em pleno funcionamento!',
  'Você é uma verdadeira máquina de produtividade! Continue fazendo coisas incríveis!',
  'Você está dominando a arte de realizar tarefas. O próximo item da lista não tem ideia do que está por vir!',
  'Está uma festa da produtividade por aqui, e você é o DJ! Toque a próxima música!',
  'Você está voando alto na escala de produtividade! Prepare-se para pousar suavemente na próxima tarefa.',
  'Você está deixando as tarefas com inveja da sua eficiência. Continue brilhando!',
  'Concluiu mais uma tarefa? Sua capa de super-herói está ficando cada vez mais estilosa!',
  'Você é a prova viva de que produtividade e diversão podem caminhar juntas. Continue se divertindo nas próximas tarefas!',
  'Impressionante! Você está arrasando mais do que um show de fogos de artifício no dia da independência!',
  'Se fossemos um jardim, você seria o botânico-chefe da produtividade. Cultive mais tarefas incríveis!',
  'Você é um verdadeiro mestre Jedi da realização de tarefas. A Força está com você!',
  'Uau, seu nível de produtividade é tão alto que até os pássaros estão aplaudindo lá fora!',
  'Estamos sem palavras! Você está transformando tarefas em obras-primas. Continue pintando o mundo com sua produtividade!',
  'Você está deixando o Sol com inveja do seu brilho de produtividade! Continue irradiando sucesso!',
  'Se as tarefas fossem troféus, você seria um campeão olímpico! Continue subindo no pódio da produtividade!',
  'Aplausos de pé! Sua produtividade está arrancando sorrisos e muitos emojis de parabéns!',
  'Seu nível de conclusão de tarefas é tão épico que merece uma trilha sonora. Aperte o play e continue sendo incrível!',
  'Você está dominando a arte de riscar tarefas da lista como um mestre da espada. A próxima batalha aguarda!',
  'Nada segura você! Sua produtividade é como um trem de alta velocidade - continue acelerando nas próximas tarefas!',
  'Você é uma máquina de produtividade tão eficiente que até os relógios estão ficando com inveja da sua pontualidade!',
  'Você é um verdadeiro embaixador da produtividade! Estamos pensando em erguer uma estátua em sua honra.',
  'Bravo! Sua produtividade está fazendo com que o universo aplauda de pé. Continue brilhando nas próximas tarefas!',
  'Uau, suas tarefas estão se rendendo ao seu talento produtivo! Continue conquistando uma após a outra!',
  'Parabéns, mestre das tarefas! Você está conquistando mais território do que um explorador em uma expedição épica!',
  'Você é uma verdadeira estrela da produtividade, iluminando o caminho para o sucesso. Continue brilhando!',
  'A cada tarefa concluída, um sorriso surge no rosto do universo. Continue espalhando alegria com sua produtividade!',
  'Uau, você está arrasando tanto nas tarefas que as metas estão pedindo autógrafos! Continue sendo um exemplo de sucesso.',
  'Você é um verdadeiro herói da produtividade! Sua superpotência: concluir tarefas em tempo recorde!',
  'Concluiu mais uma tarefa? É como marcar um gol no último minuto da partida! Continue driblando desafios!',
  'Se a produtividade fosse uma competição, você seria o medalhista de ouro! Mantenha-se no topo do pódio!',
  'Seu nível de produtividade está tão alto que as nuvens estão te aplaudindo. Continue elevando sua performance!',
  'Você está quebrando recordes de produtividade como um velocista no campo das tarefas. Continue correndo rumo ao sucesso!',
  'Você é um verdadeiro astro das tarefas, brilhando mais do que um céu estrelado. Continue sua jornada estelar!',
]

const emojis = [
  '🎉',
  '🎊',
  '👏',
  '👍',
  '🙌',
  '🤩',
  '🥳',
  '🤗',
  '🤟',
  '👌',
  '👊',
  '🤙',
  '👑',
  '🏆',
  '🥇',
  '🎯',
  '✨',
  '🌟',
  '🌈',
  '🔥',
  '🚀',
  '🎇',
]

export { emojis, quotes, titles }
