const titles = ['Parabéns', 'Uau', 'Magnífico', 'Fantástico', 'Esplêndido', 'Supimpa', 'Bom demais', 'Merece um troféu']

const quotes = [
  'Mestre das tarefas! Continue brilhando!',
  'Tarefas concluídas como um ninja! Próximo desafio!',
  'Máquina de produtividade! Recarregue e siga em frente.',
  'Eficiência em alta! Recebendo um diploma em tarefas!',
  'Estrela da produtividade! Brilhe mais!',
  'Superpoder de conclusão de tarefas!',
  'Máquina de produtividade! Continue assim!',
  'Dominando a arte das tarefas!',
  'Festa da produtividade! Toque a próxima música!',
  'Voando na escala de produtividade!',
  'Deixando as tarefas com inveja!',
  'Capa de super-herói mais estilosa!',
  'Produtividade e diversão juntas!',
  'Impressionante! Arrasando mais que fogos de artifício!',
  'Botânico-chefe da produtividade!',
  'Mestre Jedi das tarefas! A Força está com você!',
  'Nível de produtividade impressionante!',
  'Pássaros aplaudindo lá fora!',
  'Transformando tarefas em obras-primas!',
  'Deixando o Sol com inveja do seu brilho!',
  'Campeão olímpico das tarefas!',
  'Aplausos de pé!',
  'Nível épico merece trilha sonora!',
  'Dominando a arte de riscar tarefas!',
  'Nada segura você!',
  'Máquina de produtividade eficiente!',
  'Embaixador da produtividade!',
  'Fazendo o universo aplaudir de pé!',
  'Tarefas se rendendo ao seu talento!',
  'Conquistando território!',
  'Estrela da produtividade!',
  'Espalhando alegria com sua produtividade!',
  'Tarefas pedindo autógrafos!',
  'Verdadeiro herói da produtividade!',
  'Marcar um gol no último minuto!',
  'Medalhista de ouro da produtividade!',
  'Nuvens te aplaudindo!',
  'Quebrando recordes de produtividade!',
  'Astro das tarefas!',
]

const emojis = [
  '🎉',
  '🎊',
  '👏',
  '👍',
  '🙌',
  '🤩',
  '🥳',
  '🤗',
  '🤟',
  '👌',
  '👊',
  '🤙',
  '👑',
  '🏆',
  '🥇',
  '🎯',
  '✨',
  '🌟',
  '🌈',
  '🔥',
  '🚀',
  '🎇',
]

export { emojis, quotes, titles }
