const placeholders = [
  'Escrever o relatório mensal de vendas',
  'Preparar a apresentação para a reunião de equipe',
  'Enviar convites para o evento de lançamento',
  'Revisar e atualizar o plano de marketing',
  'Organizar uma sessão de brainstorming para novas ideias',
  'Agendar reunião com o cliente para discutir os requisitos',
  'Pesquisar novas tendências de mercado',
  'Desenvolver um protótipo para o novo recurso do aplicativo',
  'Criar conteúdo para as redes sociais',
  'Finalizar o design do site',
  'Fazer compras no supermercado',
  'Limpar a casa',
  'Assistir ao novo episódio da série favorita',
  'Ler um capítulo do livro atual',
  'Fazer exercícios físicos',
  'Planejar as próximas férias',
  'Cozinhar uma nova receita',
  'Escrever no diário',
  'Ligar para um amigo ou familiar',
  'Aprender uma nova habilidade online',
  'Fazer o planejamento semanal',
  'Revisar os objetivos do mês',
  'Criar uma lista de compras',
  'Organizar a papelada',
  'Enviar emails pendentes',
  'Resolver problemas de manutenção em casa',
  'Pesquisar sobre um tópico interessante',
  'Praticar um hobby criativo',
  'Estudar um novo idioma',
  'Planejar uma viagem de fim de semana',
]

export { placeholders }
